// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4lX_LJ258COqBfT7QQzDpAtECyOW5iG4',
    appId: '1:663903782058:web:53f6d25616b30795bffcd3',
    messagingSenderId: '663903782058',
    projectId: 'itinerary-b5828',
    authDomain: 'itinerary-b5828.firebaseapp.com',
    storageBucket: 'itinerary-b5828.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq2kYnZf5E-kJh0V7M8AlHSSnYQSCoY8o',
    appId: '1:663903782058:android:90b09ba9c678cee6bffcd3',
    messagingSenderId: '663903782058',
    projectId: 'itinerary-b5828',
    storageBucket: 'itinerary-b5828.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgVrQc0NiTAKyNSNNMUqi8fmgyttgDKKs',
    appId: '1:663903782058:ios:d3c8adad1accff13bffcd3',
    messagingSenderId: '663903782058',
    projectId: 'itinerary-b5828',
    storageBucket: 'itinerary-b5828.firebasestorage.app',
    iosBundleId: 'com.example.tripmateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgVrQc0NiTAKyNSNNMUqi8fmgyttgDKKs',
    appId: '1:663903782058:ios:d3c8adad1accff13bffcd3',
    messagingSenderId: '663903782058',
    projectId: 'itinerary-b5828',
    storageBucket: 'itinerary-b5828.firebasestorage.app',
    iosBundleId: 'com.example.tripmateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4lX_LJ258COqBfT7QQzDpAtECyOW5iG4',
    appId: '1:663903782058:web:4826e4716da1d82cbffcd3',
    messagingSenderId: '663903782058',
    projectId: 'itinerary-b5828',
    authDomain: 'itinerary-b5828.firebaseapp.com',
    storageBucket: 'itinerary-b5828.firebasestorage.app',
  );
}
